
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `IslamicEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model IslamicEvent
 * 
 */
export type IslamicEventModel = runtime.Types.Result.DefaultSelection<Prisma.$IslamicEventPayload>

export type AggregateIslamicEvent = {
  _count: IslamicEventCountAggregateOutputType | null
  _avg: IslamicEventAvgAggregateOutputType | null
  _sum: IslamicEventSumAggregateOutputType | null
  _min: IslamicEventMinAggregateOutputType | null
  _max: IslamicEventMaxAggregateOutputType | null
}

export type IslamicEventAvgAggregateOutputType = {
  id: number | null
}

export type IslamicEventSumAggregateOutputType = {
  id: number | null
}

export type IslamicEventMinAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  dateHijri: string | null
  estimatedGregorian: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type IslamicEventMaxAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  dateHijri: string | null
  estimatedGregorian: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type IslamicEventCountAggregateOutputType = {
  id: number
  name: number
  description: number
  dateHijri: number
  estimatedGregorian: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type IslamicEventAvgAggregateInputType = {
  id?: true
}

export type IslamicEventSumAggregateInputType = {
  id?: true
}

export type IslamicEventMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  dateHijri?: true
  estimatedGregorian?: true
  createdAt?: true
  updatedAt?: true
}

export type IslamicEventMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  dateHijri?: true
  estimatedGregorian?: true
  createdAt?: true
  updatedAt?: true
}

export type IslamicEventCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  dateHijri?: true
  estimatedGregorian?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type IslamicEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IslamicEvent to aggregate.
   */
  where?: Prisma.IslamicEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IslamicEvents to fetch.
   */
  orderBy?: Prisma.IslamicEventOrderByWithRelationInput | Prisma.IslamicEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IslamicEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IslamicEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IslamicEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned IslamicEvents
  **/
  _count?: true | IslamicEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: IslamicEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: IslamicEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IslamicEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IslamicEventMaxAggregateInputType
}

export type GetIslamicEventAggregateType<T extends IslamicEventAggregateArgs> = {
      [P in keyof T & keyof AggregateIslamicEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIslamicEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateIslamicEvent[P]>
}




export type IslamicEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IslamicEventWhereInput
  orderBy?: Prisma.IslamicEventOrderByWithAggregationInput | Prisma.IslamicEventOrderByWithAggregationInput[]
  by: Prisma.IslamicEventScalarFieldEnum[] | Prisma.IslamicEventScalarFieldEnum
  having?: Prisma.IslamicEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IslamicEventCountAggregateInputType | true
  _avg?: IslamicEventAvgAggregateInputType
  _sum?: IslamicEventSumAggregateInputType
  _min?: IslamicEventMinAggregateInputType
  _max?: IslamicEventMaxAggregateInputType
}

export type IslamicEventGroupByOutputType = {
  id: number
  name: string
  description: string | null
  dateHijri: string
  estimatedGregorian: Date | null
  createdAt: Date
  updatedAt: Date
  _count: IslamicEventCountAggregateOutputType | null
  _avg: IslamicEventAvgAggregateOutputType | null
  _sum: IslamicEventSumAggregateOutputType | null
  _min: IslamicEventMinAggregateOutputType | null
  _max: IslamicEventMaxAggregateOutputType | null
}

type GetIslamicEventGroupByPayload<T extends IslamicEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IslamicEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IslamicEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IslamicEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IslamicEventGroupByOutputType[P]>
      }
    >
  >



export type IslamicEventWhereInput = {
  AND?: Prisma.IslamicEventWhereInput | Prisma.IslamicEventWhereInput[]
  OR?: Prisma.IslamicEventWhereInput[]
  NOT?: Prisma.IslamicEventWhereInput | Prisma.IslamicEventWhereInput[]
  id?: Prisma.IntFilter<"IslamicEvent"> | number
  name?: Prisma.StringFilter<"IslamicEvent"> | string
  description?: Prisma.StringNullableFilter<"IslamicEvent"> | string | null
  dateHijri?: Prisma.StringFilter<"IslamicEvent"> | string
  estimatedGregorian?: Prisma.DateTimeNullableFilter<"IslamicEvent"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"IslamicEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"IslamicEvent"> | Date | string
}

export type IslamicEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  dateHijri?: Prisma.SortOrder
  estimatedGregorian?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IslamicEventWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.IslamicEventWhereInput | Prisma.IslamicEventWhereInput[]
  OR?: Prisma.IslamicEventWhereInput[]
  NOT?: Prisma.IslamicEventWhereInput | Prisma.IslamicEventWhereInput[]
  name?: Prisma.StringFilter<"IslamicEvent"> | string
  description?: Prisma.StringNullableFilter<"IslamicEvent"> | string | null
  dateHijri?: Prisma.StringFilter<"IslamicEvent"> | string
  estimatedGregorian?: Prisma.DateTimeNullableFilter<"IslamicEvent"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"IslamicEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"IslamicEvent"> | Date | string
}, "id">

export type IslamicEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  dateHijri?: Prisma.SortOrder
  estimatedGregorian?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.IslamicEventCountOrderByAggregateInput
  _avg?: Prisma.IslamicEventAvgOrderByAggregateInput
  _max?: Prisma.IslamicEventMaxOrderByAggregateInput
  _min?: Prisma.IslamicEventMinOrderByAggregateInput
  _sum?: Prisma.IslamicEventSumOrderByAggregateInput
}

export type IslamicEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.IslamicEventScalarWhereWithAggregatesInput | Prisma.IslamicEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.IslamicEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IslamicEventScalarWhereWithAggregatesInput | Prisma.IslamicEventScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"IslamicEvent"> | number
  name?: Prisma.StringWithAggregatesFilter<"IslamicEvent"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"IslamicEvent"> | string | null
  dateHijri?: Prisma.StringWithAggregatesFilter<"IslamicEvent"> | string
  estimatedGregorian?: Prisma.DateTimeNullableWithAggregatesFilter<"IslamicEvent"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"IslamicEvent"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"IslamicEvent"> | Date | string
}

export type IslamicEventCreateInput = {
  name: string
  description?: string | null
  dateHijri: string
  estimatedGregorian?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IslamicEventUncheckedCreateInput = {
  id?: number
  name: string
  description?: string | null
  dateHijri: string
  estimatedGregorian?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IslamicEventUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateHijri?: Prisma.StringFieldUpdateOperationsInput | string
  estimatedGregorian?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IslamicEventUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateHijri?: Prisma.StringFieldUpdateOperationsInput | string
  estimatedGregorian?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IslamicEventCreateManyInput = {
  id?: number
  name: string
  description?: string | null
  dateHijri: string
  estimatedGregorian?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IslamicEventUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateHijri?: Prisma.StringFieldUpdateOperationsInput | string
  estimatedGregorian?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IslamicEventUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateHijri?: Prisma.StringFieldUpdateOperationsInput | string
  estimatedGregorian?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IslamicEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  dateHijri?: Prisma.SortOrder
  estimatedGregorian?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IslamicEventAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IslamicEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  dateHijri?: Prisma.SortOrder
  estimatedGregorian?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IslamicEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  dateHijri?: Prisma.SortOrder
  estimatedGregorian?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IslamicEventSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type IslamicEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  dateHijri?: boolean
  estimatedGregorian?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["islamicEvent"]>

export type IslamicEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  dateHijri?: boolean
  estimatedGregorian?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["islamicEvent"]>

export type IslamicEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  dateHijri?: boolean
  estimatedGregorian?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["islamicEvent"]>

export type IslamicEventSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  dateHijri?: boolean
  estimatedGregorian?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type IslamicEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "dateHijri" | "estimatedGregorian" | "createdAt" | "updatedAt", ExtArgs["result"]["islamicEvent"]>

export type $IslamicEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "IslamicEvent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    description: string | null
    dateHijri: string
    estimatedGregorian: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["islamicEvent"]>
  composites: {}
}

export type IslamicEventGetPayload<S extends boolean | null | undefined | IslamicEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload, S>

export type IslamicEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IslamicEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IslamicEventCountAggregateInputType | true
  }

export interface IslamicEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['IslamicEvent'], meta: { name: 'IslamicEvent' } }
  /**
   * Find zero or one IslamicEvent that matches the filter.
   * @param {IslamicEventFindUniqueArgs} args - Arguments to find a IslamicEvent
   * @example
   * // Get one IslamicEvent
   * const islamicEvent = await prisma.islamicEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IslamicEventFindUniqueArgs>(args: Prisma.SelectSubset<T, IslamicEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IslamicEventClient<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one IslamicEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IslamicEventFindUniqueOrThrowArgs} args - Arguments to find a IslamicEvent
   * @example
   * // Get one IslamicEvent
   * const islamicEvent = await prisma.islamicEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IslamicEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IslamicEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IslamicEventClient<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IslamicEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IslamicEventFindFirstArgs} args - Arguments to find a IslamicEvent
   * @example
   * // Get one IslamicEvent
   * const islamicEvent = await prisma.islamicEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IslamicEventFindFirstArgs>(args?: Prisma.SelectSubset<T, IslamicEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__IslamicEventClient<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IslamicEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IslamicEventFindFirstOrThrowArgs} args - Arguments to find a IslamicEvent
   * @example
   * // Get one IslamicEvent
   * const islamicEvent = await prisma.islamicEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IslamicEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IslamicEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IslamicEventClient<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more IslamicEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IslamicEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all IslamicEvents
   * const islamicEvents = await prisma.islamicEvent.findMany()
   * 
   * // Get first 10 IslamicEvents
   * const islamicEvents = await prisma.islamicEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const islamicEventWithIdOnly = await prisma.islamicEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IslamicEventFindManyArgs>(args?: Prisma.SelectSubset<T, IslamicEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a IslamicEvent.
   * @param {IslamicEventCreateArgs} args - Arguments to create a IslamicEvent.
   * @example
   * // Create one IslamicEvent
   * const IslamicEvent = await prisma.islamicEvent.create({
   *   data: {
   *     // ... data to create a IslamicEvent
   *   }
   * })
   * 
   */
  create<T extends IslamicEventCreateArgs>(args: Prisma.SelectSubset<T, IslamicEventCreateArgs<ExtArgs>>): Prisma.Prisma__IslamicEventClient<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many IslamicEvents.
   * @param {IslamicEventCreateManyArgs} args - Arguments to create many IslamicEvents.
   * @example
   * // Create many IslamicEvents
   * const islamicEvent = await prisma.islamicEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IslamicEventCreateManyArgs>(args?: Prisma.SelectSubset<T, IslamicEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many IslamicEvents and returns the data saved in the database.
   * @param {IslamicEventCreateManyAndReturnArgs} args - Arguments to create many IslamicEvents.
   * @example
   * // Create many IslamicEvents
   * const islamicEvent = await prisma.islamicEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many IslamicEvents and only return the `id`
   * const islamicEventWithIdOnly = await prisma.islamicEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IslamicEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IslamicEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a IslamicEvent.
   * @param {IslamicEventDeleteArgs} args - Arguments to delete one IslamicEvent.
   * @example
   * // Delete one IslamicEvent
   * const IslamicEvent = await prisma.islamicEvent.delete({
   *   where: {
   *     // ... filter to delete one IslamicEvent
   *   }
   * })
   * 
   */
  delete<T extends IslamicEventDeleteArgs>(args: Prisma.SelectSubset<T, IslamicEventDeleteArgs<ExtArgs>>): Prisma.Prisma__IslamicEventClient<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one IslamicEvent.
   * @param {IslamicEventUpdateArgs} args - Arguments to update one IslamicEvent.
   * @example
   * // Update one IslamicEvent
   * const islamicEvent = await prisma.islamicEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IslamicEventUpdateArgs>(args: Prisma.SelectSubset<T, IslamicEventUpdateArgs<ExtArgs>>): Prisma.Prisma__IslamicEventClient<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more IslamicEvents.
   * @param {IslamicEventDeleteManyArgs} args - Arguments to filter IslamicEvents to delete.
   * @example
   * // Delete a few IslamicEvents
   * const { count } = await prisma.islamicEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IslamicEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, IslamicEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IslamicEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IslamicEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many IslamicEvents
   * const islamicEvent = await prisma.islamicEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IslamicEventUpdateManyArgs>(args: Prisma.SelectSubset<T, IslamicEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IslamicEvents and returns the data updated in the database.
   * @param {IslamicEventUpdateManyAndReturnArgs} args - Arguments to update many IslamicEvents.
   * @example
   * // Update many IslamicEvents
   * const islamicEvent = await prisma.islamicEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more IslamicEvents and only return the `id`
   * const islamicEventWithIdOnly = await prisma.islamicEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IslamicEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IslamicEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one IslamicEvent.
   * @param {IslamicEventUpsertArgs} args - Arguments to update or create a IslamicEvent.
   * @example
   * // Update or create a IslamicEvent
   * const islamicEvent = await prisma.islamicEvent.upsert({
   *   create: {
   *     // ... data to create a IslamicEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the IslamicEvent we want to update
   *   }
   * })
   */
  upsert<T extends IslamicEventUpsertArgs>(args: Prisma.SelectSubset<T, IslamicEventUpsertArgs<ExtArgs>>): Prisma.Prisma__IslamicEventClient<runtime.Types.Result.GetResult<Prisma.$IslamicEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of IslamicEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IslamicEventCountArgs} args - Arguments to filter IslamicEvents to count.
   * @example
   * // Count the number of IslamicEvents
   * const count = await prisma.islamicEvent.count({
   *   where: {
   *     // ... the filter for the IslamicEvents we want to count
   *   }
   * })
  **/
  count<T extends IslamicEventCountArgs>(
    args?: Prisma.Subset<T, IslamicEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IslamicEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a IslamicEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IslamicEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IslamicEventAggregateArgs>(args: Prisma.Subset<T, IslamicEventAggregateArgs>): Prisma.PrismaPromise<GetIslamicEventAggregateType<T>>

  /**
   * Group by IslamicEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IslamicEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IslamicEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IslamicEventGroupByArgs['orderBy'] }
      : { orderBy?: IslamicEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IslamicEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIslamicEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the IslamicEvent model
 */
readonly fields: IslamicEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for IslamicEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IslamicEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the IslamicEvent model
 */
export interface IslamicEventFieldRefs {
  readonly id: Prisma.FieldRef<"IslamicEvent", 'Int'>
  readonly name: Prisma.FieldRef<"IslamicEvent", 'String'>
  readonly description: Prisma.FieldRef<"IslamicEvent", 'String'>
  readonly dateHijri: Prisma.FieldRef<"IslamicEvent", 'String'>
  readonly estimatedGregorian: Prisma.FieldRef<"IslamicEvent", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"IslamicEvent", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"IslamicEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * IslamicEvent findUnique
 */
export type IslamicEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * Filter, which IslamicEvent to fetch.
   */
  where: Prisma.IslamicEventWhereUniqueInput
}

/**
 * IslamicEvent findUniqueOrThrow
 */
export type IslamicEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * Filter, which IslamicEvent to fetch.
   */
  where: Prisma.IslamicEventWhereUniqueInput
}

/**
 * IslamicEvent findFirst
 */
export type IslamicEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * Filter, which IslamicEvent to fetch.
   */
  where?: Prisma.IslamicEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IslamicEvents to fetch.
   */
  orderBy?: Prisma.IslamicEventOrderByWithRelationInput | Prisma.IslamicEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IslamicEvents.
   */
  cursor?: Prisma.IslamicEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IslamicEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IslamicEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IslamicEvents.
   */
  distinct?: Prisma.IslamicEventScalarFieldEnum | Prisma.IslamicEventScalarFieldEnum[]
}

/**
 * IslamicEvent findFirstOrThrow
 */
export type IslamicEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * Filter, which IslamicEvent to fetch.
   */
  where?: Prisma.IslamicEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IslamicEvents to fetch.
   */
  orderBy?: Prisma.IslamicEventOrderByWithRelationInput | Prisma.IslamicEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IslamicEvents.
   */
  cursor?: Prisma.IslamicEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IslamicEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IslamicEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IslamicEvents.
   */
  distinct?: Prisma.IslamicEventScalarFieldEnum | Prisma.IslamicEventScalarFieldEnum[]
}

/**
 * IslamicEvent findMany
 */
export type IslamicEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * Filter, which IslamicEvents to fetch.
   */
  where?: Prisma.IslamicEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IslamicEvents to fetch.
   */
  orderBy?: Prisma.IslamicEventOrderByWithRelationInput | Prisma.IslamicEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing IslamicEvents.
   */
  cursor?: Prisma.IslamicEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IslamicEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IslamicEvents.
   */
  skip?: number
  distinct?: Prisma.IslamicEventScalarFieldEnum | Prisma.IslamicEventScalarFieldEnum[]
}

/**
 * IslamicEvent create
 */
export type IslamicEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * The data needed to create a IslamicEvent.
   */
  data: Prisma.XOR<Prisma.IslamicEventCreateInput, Prisma.IslamicEventUncheckedCreateInput>
}

/**
 * IslamicEvent createMany
 */
export type IslamicEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many IslamicEvents.
   */
  data: Prisma.IslamicEventCreateManyInput | Prisma.IslamicEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * IslamicEvent createManyAndReturn
 */
export type IslamicEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * The data used to create many IslamicEvents.
   */
  data: Prisma.IslamicEventCreateManyInput | Prisma.IslamicEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * IslamicEvent update
 */
export type IslamicEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * The data needed to update a IslamicEvent.
   */
  data: Prisma.XOR<Prisma.IslamicEventUpdateInput, Prisma.IslamicEventUncheckedUpdateInput>
  /**
   * Choose, which IslamicEvent to update.
   */
  where: Prisma.IslamicEventWhereUniqueInput
}

/**
 * IslamicEvent updateMany
 */
export type IslamicEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update IslamicEvents.
   */
  data: Prisma.XOR<Prisma.IslamicEventUpdateManyMutationInput, Prisma.IslamicEventUncheckedUpdateManyInput>
  /**
   * Filter which IslamicEvents to update
   */
  where?: Prisma.IslamicEventWhereInput
  /**
   * Limit how many IslamicEvents to update.
   */
  limit?: number
}

/**
 * IslamicEvent updateManyAndReturn
 */
export type IslamicEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * The data used to update IslamicEvents.
   */
  data: Prisma.XOR<Prisma.IslamicEventUpdateManyMutationInput, Prisma.IslamicEventUncheckedUpdateManyInput>
  /**
   * Filter which IslamicEvents to update
   */
  where?: Prisma.IslamicEventWhereInput
  /**
   * Limit how many IslamicEvents to update.
   */
  limit?: number
}

/**
 * IslamicEvent upsert
 */
export type IslamicEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * The filter to search for the IslamicEvent to update in case it exists.
   */
  where: Prisma.IslamicEventWhereUniqueInput
  /**
   * In case the IslamicEvent found by the `where` argument doesn't exist, create a new IslamicEvent with this data.
   */
  create: Prisma.XOR<Prisma.IslamicEventCreateInput, Prisma.IslamicEventUncheckedCreateInput>
  /**
   * In case the IslamicEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IslamicEventUpdateInput, Prisma.IslamicEventUncheckedUpdateInput>
}

/**
 * IslamicEvent delete
 */
export type IslamicEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
  /**
   * Filter which IslamicEvent to delete.
   */
  where: Prisma.IslamicEventWhereUniqueInput
}

/**
 * IslamicEvent deleteMany
 */
export type IslamicEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IslamicEvents to delete
   */
  where?: Prisma.IslamicEventWhereInput
  /**
   * Limit how many IslamicEvents to delete.
   */
  limit?: number
}

/**
 * IslamicEvent without action
 */
export type IslamicEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IslamicEvent
   */
  select?: Prisma.IslamicEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IslamicEvent
   */
  omit?: Prisma.IslamicEventOmit<ExtArgs> | null
}
