
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NotificationSchedule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model NotificationSchedule
 * 
 */
export type NotificationScheduleModel = runtime.Types.Result.DefaultSelection<Prisma.$NotificationSchedulePayload>

export type AggregateNotificationSchedule = {
  _count: NotificationScheduleCountAggregateOutputType | null
  _avg: NotificationScheduleAvgAggregateOutputType | null
  _sum: NotificationScheduleSumAggregateOutputType | null
  _min: NotificationScheduleMinAggregateOutputType | null
  _max: NotificationScheduleMaxAggregateOutputType | null
}

export type NotificationScheduleAvgAggregateOutputType = {
  id: number | null
}

export type NotificationScheduleSumAggregateOutputType = {
  id: number | null
}

export type NotificationScheduleMinAggregateOutputType = {
  id: number | null
  type: $Enums.NotificationType | null
  title: string | null
  body: string | null
  scheduleAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NotificationScheduleMaxAggregateOutputType = {
  id: number | null
  type: $Enums.NotificationType | null
  title: string | null
  body: string | null
  scheduleAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NotificationScheduleCountAggregateOutputType = {
  id: number
  type: number
  title: number
  body: number
  scheduleAt: number
  meta: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type NotificationScheduleAvgAggregateInputType = {
  id?: true
}

export type NotificationScheduleSumAggregateInputType = {
  id?: true
}

export type NotificationScheduleMinAggregateInputType = {
  id?: true
  type?: true
  title?: true
  body?: true
  scheduleAt?: true
  createdAt?: true
  updatedAt?: true
}

export type NotificationScheduleMaxAggregateInputType = {
  id?: true
  type?: true
  title?: true
  body?: true
  scheduleAt?: true
  createdAt?: true
  updatedAt?: true
}

export type NotificationScheduleCountAggregateInputType = {
  id?: true
  type?: true
  title?: true
  body?: true
  scheduleAt?: true
  meta?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type NotificationScheduleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NotificationSchedule to aggregate.
   */
  where?: Prisma.NotificationScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationSchedules to fetch.
   */
  orderBy?: Prisma.NotificationScheduleOrderByWithRelationInput | Prisma.NotificationScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NotificationScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NotificationSchedules
  **/
  _count?: true | NotificationScheduleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NotificationScheduleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NotificationScheduleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NotificationScheduleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NotificationScheduleMaxAggregateInputType
}

export type GetNotificationScheduleAggregateType<T extends NotificationScheduleAggregateArgs> = {
      [P in keyof T & keyof AggregateNotificationSchedule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNotificationSchedule[P]>
    : Prisma.GetScalarType<T[P], AggregateNotificationSchedule[P]>
}




export type NotificationScheduleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationScheduleWhereInput
  orderBy?: Prisma.NotificationScheduleOrderByWithAggregationInput | Prisma.NotificationScheduleOrderByWithAggregationInput[]
  by: Prisma.NotificationScheduleScalarFieldEnum[] | Prisma.NotificationScheduleScalarFieldEnum
  having?: Prisma.NotificationScheduleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NotificationScheduleCountAggregateInputType | true
  _avg?: NotificationScheduleAvgAggregateInputType
  _sum?: NotificationScheduleSumAggregateInputType
  _min?: NotificationScheduleMinAggregateInputType
  _max?: NotificationScheduleMaxAggregateInputType
}

export type NotificationScheduleGroupByOutputType = {
  id: number
  type: $Enums.NotificationType
  title: string
  body: string
  scheduleAt: Date
  meta: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: NotificationScheduleCountAggregateOutputType | null
  _avg: NotificationScheduleAvgAggregateOutputType | null
  _sum: NotificationScheduleSumAggregateOutputType | null
  _min: NotificationScheduleMinAggregateOutputType | null
  _max: NotificationScheduleMaxAggregateOutputType | null
}

type GetNotificationScheduleGroupByPayload<T extends NotificationScheduleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NotificationScheduleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NotificationScheduleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NotificationScheduleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NotificationScheduleGroupByOutputType[P]>
      }
    >
  >



export type NotificationScheduleWhereInput = {
  AND?: Prisma.NotificationScheduleWhereInput | Prisma.NotificationScheduleWhereInput[]
  OR?: Prisma.NotificationScheduleWhereInput[]
  NOT?: Prisma.NotificationScheduleWhereInput | Prisma.NotificationScheduleWhereInput[]
  id?: Prisma.IntFilter<"NotificationSchedule"> | number
  type?: Prisma.EnumNotificationTypeFilter<"NotificationSchedule"> | $Enums.NotificationType
  title?: Prisma.StringFilter<"NotificationSchedule"> | string
  body?: Prisma.StringFilter<"NotificationSchedule"> | string
  scheduleAt?: Prisma.DateTimeFilter<"NotificationSchedule"> | Date | string
  meta?: Prisma.JsonNullableFilter<"NotificationSchedule">
  createdAt?: Prisma.DateTimeFilter<"NotificationSchedule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NotificationSchedule"> | Date | string
}

export type NotificationScheduleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  scheduleAt?: Prisma.SortOrder
  meta?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotificationScheduleWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.NotificationScheduleWhereInput | Prisma.NotificationScheduleWhereInput[]
  OR?: Prisma.NotificationScheduleWhereInput[]
  NOT?: Prisma.NotificationScheduleWhereInput | Prisma.NotificationScheduleWhereInput[]
  type?: Prisma.EnumNotificationTypeFilter<"NotificationSchedule"> | $Enums.NotificationType
  title?: Prisma.StringFilter<"NotificationSchedule"> | string
  body?: Prisma.StringFilter<"NotificationSchedule"> | string
  scheduleAt?: Prisma.DateTimeFilter<"NotificationSchedule"> | Date | string
  meta?: Prisma.JsonNullableFilter<"NotificationSchedule">
  createdAt?: Prisma.DateTimeFilter<"NotificationSchedule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NotificationSchedule"> | Date | string
}, "id">

export type NotificationScheduleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  scheduleAt?: Prisma.SortOrder
  meta?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.NotificationScheduleCountOrderByAggregateInput
  _avg?: Prisma.NotificationScheduleAvgOrderByAggregateInput
  _max?: Prisma.NotificationScheduleMaxOrderByAggregateInput
  _min?: Prisma.NotificationScheduleMinOrderByAggregateInput
  _sum?: Prisma.NotificationScheduleSumOrderByAggregateInput
}

export type NotificationScheduleScalarWhereWithAggregatesInput = {
  AND?: Prisma.NotificationScheduleScalarWhereWithAggregatesInput | Prisma.NotificationScheduleScalarWhereWithAggregatesInput[]
  OR?: Prisma.NotificationScheduleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NotificationScheduleScalarWhereWithAggregatesInput | Prisma.NotificationScheduleScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"NotificationSchedule"> | number
  type?: Prisma.EnumNotificationTypeWithAggregatesFilter<"NotificationSchedule"> | $Enums.NotificationType
  title?: Prisma.StringWithAggregatesFilter<"NotificationSchedule"> | string
  body?: Prisma.StringWithAggregatesFilter<"NotificationSchedule"> | string
  scheduleAt?: Prisma.DateTimeWithAggregatesFilter<"NotificationSchedule"> | Date | string
  meta?: Prisma.JsonNullableWithAggregatesFilter<"NotificationSchedule">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NotificationSchedule"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"NotificationSchedule"> | Date | string
}

export type NotificationScheduleCreateInput = {
  type: $Enums.NotificationType
  title: string
  body: string
  scheduleAt: Date | string
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotificationScheduleUncheckedCreateInput = {
  id?: number
  type: $Enums.NotificationType
  title: string
  body: string
  scheduleAt: Date | string
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotificationScheduleUpdateInput = {
  type?: Prisma.EnumNotificationTypeFieldUpdateOperationsInput | $Enums.NotificationType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  scheduleAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationScheduleUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumNotificationTypeFieldUpdateOperationsInput | $Enums.NotificationType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  scheduleAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationScheduleCreateManyInput = {
  id?: number
  type: $Enums.NotificationType
  title: string
  body: string
  scheduleAt: Date | string
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotificationScheduleUpdateManyMutationInput = {
  type?: Prisma.EnumNotificationTypeFieldUpdateOperationsInput | $Enums.NotificationType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  scheduleAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationScheduleUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumNotificationTypeFieldUpdateOperationsInput | $Enums.NotificationType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  scheduleAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationScheduleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  scheduleAt?: Prisma.SortOrder
  meta?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotificationScheduleAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NotificationScheduleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  scheduleAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotificationScheduleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  scheduleAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotificationScheduleSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type EnumNotificationTypeFieldUpdateOperationsInput = {
  set?: $Enums.NotificationType
}



export type NotificationScheduleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  title?: boolean
  body?: boolean
  scheduleAt?: boolean
  meta?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["notificationSchedule"]>

export type NotificationScheduleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  title?: boolean
  body?: boolean
  scheduleAt?: boolean
  meta?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["notificationSchedule"]>

export type NotificationScheduleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  title?: boolean
  body?: boolean
  scheduleAt?: boolean
  meta?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["notificationSchedule"]>

export type NotificationScheduleSelectScalar = {
  id?: boolean
  type?: boolean
  title?: boolean
  body?: boolean
  scheduleAt?: boolean
  meta?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type NotificationScheduleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "title" | "body" | "scheduleAt" | "meta" | "createdAt" | "updatedAt", ExtArgs["result"]["notificationSchedule"]>

export type $NotificationSchedulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NotificationSchedule"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    type: $Enums.NotificationType
    title: string
    body: string
    scheduleAt: Date
    meta: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["notificationSchedule"]>
  composites: {}
}

export type NotificationScheduleGetPayload<S extends boolean | null | undefined | NotificationScheduleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload, S>

export type NotificationScheduleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NotificationScheduleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NotificationScheduleCountAggregateInputType | true
  }

export interface NotificationScheduleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NotificationSchedule'], meta: { name: 'NotificationSchedule' } }
  /**
   * Find zero or one NotificationSchedule that matches the filter.
   * @param {NotificationScheduleFindUniqueArgs} args - Arguments to find a NotificationSchedule
   * @example
   * // Get one NotificationSchedule
   * const notificationSchedule = await prisma.notificationSchedule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NotificationScheduleFindUniqueArgs>(args: Prisma.SelectSubset<T, NotificationScheduleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NotificationScheduleClient<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NotificationSchedule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NotificationScheduleFindUniqueOrThrowArgs} args - Arguments to find a NotificationSchedule
   * @example
   * // Get one NotificationSchedule
   * const notificationSchedule = await prisma.notificationSchedule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NotificationScheduleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NotificationScheduleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationScheduleClient<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NotificationSchedule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationScheduleFindFirstArgs} args - Arguments to find a NotificationSchedule
   * @example
   * // Get one NotificationSchedule
   * const notificationSchedule = await prisma.notificationSchedule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NotificationScheduleFindFirstArgs>(args?: Prisma.SelectSubset<T, NotificationScheduleFindFirstArgs<ExtArgs>>): Prisma.Prisma__NotificationScheduleClient<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NotificationSchedule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationScheduleFindFirstOrThrowArgs} args - Arguments to find a NotificationSchedule
   * @example
   * // Get one NotificationSchedule
   * const notificationSchedule = await prisma.notificationSchedule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NotificationScheduleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NotificationScheduleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationScheduleClient<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NotificationSchedules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationScheduleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NotificationSchedules
   * const notificationSchedules = await prisma.notificationSchedule.findMany()
   * 
   * // Get first 10 NotificationSchedules
   * const notificationSchedules = await prisma.notificationSchedule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const notificationScheduleWithIdOnly = await prisma.notificationSchedule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NotificationScheduleFindManyArgs>(args?: Prisma.SelectSubset<T, NotificationScheduleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NotificationSchedule.
   * @param {NotificationScheduleCreateArgs} args - Arguments to create a NotificationSchedule.
   * @example
   * // Create one NotificationSchedule
   * const NotificationSchedule = await prisma.notificationSchedule.create({
   *   data: {
   *     // ... data to create a NotificationSchedule
   *   }
   * })
   * 
   */
  create<T extends NotificationScheduleCreateArgs>(args: Prisma.SelectSubset<T, NotificationScheduleCreateArgs<ExtArgs>>): Prisma.Prisma__NotificationScheduleClient<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NotificationSchedules.
   * @param {NotificationScheduleCreateManyArgs} args - Arguments to create many NotificationSchedules.
   * @example
   * // Create many NotificationSchedules
   * const notificationSchedule = await prisma.notificationSchedule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NotificationScheduleCreateManyArgs>(args?: Prisma.SelectSubset<T, NotificationScheduleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NotificationSchedules and returns the data saved in the database.
   * @param {NotificationScheduleCreateManyAndReturnArgs} args - Arguments to create many NotificationSchedules.
   * @example
   * // Create many NotificationSchedules
   * const notificationSchedule = await prisma.notificationSchedule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NotificationSchedules and only return the `id`
   * const notificationScheduleWithIdOnly = await prisma.notificationSchedule.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NotificationScheduleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NotificationScheduleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NotificationSchedule.
   * @param {NotificationScheduleDeleteArgs} args - Arguments to delete one NotificationSchedule.
   * @example
   * // Delete one NotificationSchedule
   * const NotificationSchedule = await prisma.notificationSchedule.delete({
   *   where: {
   *     // ... filter to delete one NotificationSchedule
   *   }
   * })
   * 
   */
  delete<T extends NotificationScheduleDeleteArgs>(args: Prisma.SelectSubset<T, NotificationScheduleDeleteArgs<ExtArgs>>): Prisma.Prisma__NotificationScheduleClient<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NotificationSchedule.
   * @param {NotificationScheduleUpdateArgs} args - Arguments to update one NotificationSchedule.
   * @example
   * // Update one NotificationSchedule
   * const notificationSchedule = await prisma.notificationSchedule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NotificationScheduleUpdateArgs>(args: Prisma.SelectSubset<T, NotificationScheduleUpdateArgs<ExtArgs>>): Prisma.Prisma__NotificationScheduleClient<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NotificationSchedules.
   * @param {NotificationScheduleDeleteManyArgs} args - Arguments to filter NotificationSchedules to delete.
   * @example
   * // Delete a few NotificationSchedules
   * const { count } = await prisma.notificationSchedule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NotificationScheduleDeleteManyArgs>(args?: Prisma.SelectSubset<T, NotificationScheduleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NotificationSchedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationScheduleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NotificationSchedules
   * const notificationSchedule = await prisma.notificationSchedule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NotificationScheduleUpdateManyArgs>(args: Prisma.SelectSubset<T, NotificationScheduleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NotificationSchedules and returns the data updated in the database.
   * @param {NotificationScheduleUpdateManyAndReturnArgs} args - Arguments to update many NotificationSchedules.
   * @example
   * // Update many NotificationSchedules
   * const notificationSchedule = await prisma.notificationSchedule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NotificationSchedules and only return the `id`
   * const notificationScheduleWithIdOnly = await prisma.notificationSchedule.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NotificationScheduleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NotificationScheduleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NotificationSchedule.
   * @param {NotificationScheduleUpsertArgs} args - Arguments to update or create a NotificationSchedule.
   * @example
   * // Update or create a NotificationSchedule
   * const notificationSchedule = await prisma.notificationSchedule.upsert({
   *   create: {
   *     // ... data to create a NotificationSchedule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NotificationSchedule we want to update
   *   }
   * })
   */
  upsert<T extends NotificationScheduleUpsertArgs>(args: Prisma.SelectSubset<T, NotificationScheduleUpsertArgs<ExtArgs>>): Prisma.Prisma__NotificationScheduleClient<runtime.Types.Result.GetResult<Prisma.$NotificationSchedulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NotificationSchedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationScheduleCountArgs} args - Arguments to filter NotificationSchedules to count.
   * @example
   * // Count the number of NotificationSchedules
   * const count = await prisma.notificationSchedule.count({
   *   where: {
   *     // ... the filter for the NotificationSchedules we want to count
   *   }
   * })
  **/
  count<T extends NotificationScheduleCountArgs>(
    args?: Prisma.Subset<T, NotificationScheduleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NotificationScheduleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NotificationSchedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationScheduleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NotificationScheduleAggregateArgs>(args: Prisma.Subset<T, NotificationScheduleAggregateArgs>): Prisma.PrismaPromise<GetNotificationScheduleAggregateType<T>>

  /**
   * Group by NotificationSchedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationScheduleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NotificationScheduleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NotificationScheduleGroupByArgs['orderBy'] }
      : { orderBy?: NotificationScheduleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NotificationScheduleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNotificationScheduleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NotificationSchedule model
 */
readonly fields: NotificationScheduleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NotificationSchedule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NotificationScheduleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NotificationSchedule model
 */
export interface NotificationScheduleFieldRefs {
  readonly id: Prisma.FieldRef<"NotificationSchedule", 'Int'>
  readonly type: Prisma.FieldRef<"NotificationSchedule", 'NotificationType'>
  readonly title: Prisma.FieldRef<"NotificationSchedule", 'String'>
  readonly body: Prisma.FieldRef<"NotificationSchedule", 'String'>
  readonly scheduleAt: Prisma.FieldRef<"NotificationSchedule", 'DateTime'>
  readonly meta: Prisma.FieldRef<"NotificationSchedule", 'Json'>
  readonly createdAt: Prisma.FieldRef<"NotificationSchedule", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"NotificationSchedule", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NotificationSchedule findUnique
 */
export type NotificationScheduleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * Filter, which NotificationSchedule to fetch.
   */
  where: Prisma.NotificationScheduleWhereUniqueInput
}

/**
 * NotificationSchedule findUniqueOrThrow
 */
export type NotificationScheduleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * Filter, which NotificationSchedule to fetch.
   */
  where: Prisma.NotificationScheduleWhereUniqueInput
}

/**
 * NotificationSchedule findFirst
 */
export type NotificationScheduleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * Filter, which NotificationSchedule to fetch.
   */
  where?: Prisma.NotificationScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationSchedules to fetch.
   */
  orderBy?: Prisma.NotificationScheduleOrderByWithRelationInput | Prisma.NotificationScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NotificationSchedules.
   */
  cursor?: Prisma.NotificationScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NotificationSchedules.
   */
  distinct?: Prisma.NotificationScheduleScalarFieldEnum | Prisma.NotificationScheduleScalarFieldEnum[]
}

/**
 * NotificationSchedule findFirstOrThrow
 */
export type NotificationScheduleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * Filter, which NotificationSchedule to fetch.
   */
  where?: Prisma.NotificationScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationSchedules to fetch.
   */
  orderBy?: Prisma.NotificationScheduleOrderByWithRelationInput | Prisma.NotificationScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NotificationSchedules.
   */
  cursor?: Prisma.NotificationScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NotificationSchedules.
   */
  distinct?: Prisma.NotificationScheduleScalarFieldEnum | Prisma.NotificationScheduleScalarFieldEnum[]
}

/**
 * NotificationSchedule findMany
 */
export type NotificationScheduleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * Filter, which NotificationSchedules to fetch.
   */
  where?: Prisma.NotificationScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationSchedules to fetch.
   */
  orderBy?: Prisma.NotificationScheduleOrderByWithRelationInput | Prisma.NotificationScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NotificationSchedules.
   */
  cursor?: Prisma.NotificationScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationSchedules.
   */
  skip?: number
  distinct?: Prisma.NotificationScheduleScalarFieldEnum | Prisma.NotificationScheduleScalarFieldEnum[]
}

/**
 * NotificationSchedule create
 */
export type NotificationScheduleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * The data needed to create a NotificationSchedule.
   */
  data: Prisma.XOR<Prisma.NotificationScheduleCreateInput, Prisma.NotificationScheduleUncheckedCreateInput>
}

/**
 * NotificationSchedule createMany
 */
export type NotificationScheduleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NotificationSchedules.
   */
  data: Prisma.NotificationScheduleCreateManyInput | Prisma.NotificationScheduleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NotificationSchedule createManyAndReturn
 */
export type NotificationScheduleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * The data used to create many NotificationSchedules.
   */
  data: Prisma.NotificationScheduleCreateManyInput | Prisma.NotificationScheduleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NotificationSchedule update
 */
export type NotificationScheduleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * The data needed to update a NotificationSchedule.
   */
  data: Prisma.XOR<Prisma.NotificationScheduleUpdateInput, Prisma.NotificationScheduleUncheckedUpdateInput>
  /**
   * Choose, which NotificationSchedule to update.
   */
  where: Prisma.NotificationScheduleWhereUniqueInput
}

/**
 * NotificationSchedule updateMany
 */
export type NotificationScheduleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NotificationSchedules.
   */
  data: Prisma.XOR<Prisma.NotificationScheduleUpdateManyMutationInput, Prisma.NotificationScheduleUncheckedUpdateManyInput>
  /**
   * Filter which NotificationSchedules to update
   */
  where?: Prisma.NotificationScheduleWhereInput
  /**
   * Limit how many NotificationSchedules to update.
   */
  limit?: number
}

/**
 * NotificationSchedule updateManyAndReturn
 */
export type NotificationScheduleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * The data used to update NotificationSchedules.
   */
  data: Prisma.XOR<Prisma.NotificationScheduleUpdateManyMutationInput, Prisma.NotificationScheduleUncheckedUpdateManyInput>
  /**
   * Filter which NotificationSchedules to update
   */
  where?: Prisma.NotificationScheduleWhereInput
  /**
   * Limit how many NotificationSchedules to update.
   */
  limit?: number
}

/**
 * NotificationSchedule upsert
 */
export type NotificationScheduleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * The filter to search for the NotificationSchedule to update in case it exists.
   */
  where: Prisma.NotificationScheduleWhereUniqueInput
  /**
   * In case the NotificationSchedule found by the `where` argument doesn't exist, create a new NotificationSchedule with this data.
   */
  create: Prisma.XOR<Prisma.NotificationScheduleCreateInput, Prisma.NotificationScheduleUncheckedCreateInput>
  /**
   * In case the NotificationSchedule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NotificationScheduleUpdateInput, Prisma.NotificationScheduleUncheckedUpdateInput>
}

/**
 * NotificationSchedule delete
 */
export type NotificationScheduleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
  /**
   * Filter which NotificationSchedule to delete.
   */
  where: Prisma.NotificationScheduleWhereUniqueInput
}

/**
 * NotificationSchedule deleteMany
 */
export type NotificationScheduleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NotificationSchedules to delete
   */
  where?: Prisma.NotificationScheduleWhereInput
  /**
   * Limit how many NotificationSchedules to delete.
   */
  limit?: number
}

/**
 * NotificationSchedule without action
 */
export type NotificationScheduleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSchedule
   */
  select?: Prisma.NotificationScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSchedule
   */
  omit?: Prisma.NotificationScheduleOmit<ExtArgs> | null
}
