
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PrayerCache` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PrayerCache
 * 
 */
export type PrayerCacheModel = runtime.Types.Result.DefaultSelection<Prisma.$PrayerCachePayload>

export type AggregatePrayerCache = {
  _count: PrayerCacheCountAggregateOutputType | null
  _avg: PrayerCacheAvgAggregateOutputType | null
  _sum: PrayerCacheSumAggregateOutputType | null
  _min: PrayerCacheMinAggregateOutputType | null
  _max: PrayerCacheMaxAggregateOutputType | null
}

export type PrayerCacheAvgAggregateOutputType = {
  id: number | null
}

export type PrayerCacheSumAggregateOutputType = {
  id: number | null
}

export type PrayerCacheMinAggregateOutputType = {
  id: number | null
  date: Date | null
  fajr: string | null
  dhuhr: string | null
  asr: string | null
  maghrib: string | null
  isha: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PrayerCacheMaxAggregateOutputType = {
  id: number | null
  date: Date | null
  fajr: string | null
  dhuhr: string | null
  asr: string | null
  maghrib: string | null
  isha: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PrayerCacheCountAggregateOutputType = {
  id: number
  date: number
  fajr: number
  dhuhr: number
  asr: number
  maghrib: number
  isha: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PrayerCacheAvgAggregateInputType = {
  id?: true
}

export type PrayerCacheSumAggregateInputType = {
  id?: true
}

export type PrayerCacheMinAggregateInputType = {
  id?: true
  date?: true
  fajr?: true
  dhuhr?: true
  asr?: true
  maghrib?: true
  isha?: true
  createdAt?: true
  updatedAt?: true
}

export type PrayerCacheMaxAggregateInputType = {
  id?: true
  date?: true
  fajr?: true
  dhuhr?: true
  asr?: true
  maghrib?: true
  isha?: true
  createdAt?: true
  updatedAt?: true
}

export type PrayerCacheCountAggregateInputType = {
  id?: true
  date?: true
  fajr?: true
  dhuhr?: true
  asr?: true
  maghrib?: true
  isha?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PrayerCacheAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PrayerCache to aggregate.
   */
  where?: Prisma.PrayerCacheWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrayerCaches to fetch.
   */
  orderBy?: Prisma.PrayerCacheOrderByWithRelationInput | Prisma.PrayerCacheOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PrayerCacheWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrayerCaches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrayerCaches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PrayerCaches
  **/
  _count?: true | PrayerCacheCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PrayerCacheAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PrayerCacheSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PrayerCacheMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PrayerCacheMaxAggregateInputType
}

export type GetPrayerCacheAggregateType<T extends PrayerCacheAggregateArgs> = {
      [P in keyof T & keyof AggregatePrayerCache]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePrayerCache[P]>
    : Prisma.GetScalarType<T[P], AggregatePrayerCache[P]>
}




export type PrayerCacheGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PrayerCacheWhereInput
  orderBy?: Prisma.PrayerCacheOrderByWithAggregationInput | Prisma.PrayerCacheOrderByWithAggregationInput[]
  by: Prisma.PrayerCacheScalarFieldEnum[] | Prisma.PrayerCacheScalarFieldEnum
  having?: Prisma.PrayerCacheScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PrayerCacheCountAggregateInputType | true
  _avg?: PrayerCacheAvgAggregateInputType
  _sum?: PrayerCacheSumAggregateInputType
  _min?: PrayerCacheMinAggregateInputType
  _max?: PrayerCacheMaxAggregateInputType
}

export type PrayerCacheGroupByOutputType = {
  id: number
  date: Date
  fajr: string
  dhuhr: string
  asr: string
  maghrib: string
  isha: string
  createdAt: Date
  updatedAt: Date
  _count: PrayerCacheCountAggregateOutputType | null
  _avg: PrayerCacheAvgAggregateOutputType | null
  _sum: PrayerCacheSumAggregateOutputType | null
  _min: PrayerCacheMinAggregateOutputType | null
  _max: PrayerCacheMaxAggregateOutputType | null
}

type GetPrayerCacheGroupByPayload<T extends PrayerCacheGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PrayerCacheGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PrayerCacheGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PrayerCacheGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PrayerCacheGroupByOutputType[P]>
      }
    >
  >



export type PrayerCacheWhereInput = {
  AND?: Prisma.PrayerCacheWhereInput | Prisma.PrayerCacheWhereInput[]
  OR?: Prisma.PrayerCacheWhereInput[]
  NOT?: Prisma.PrayerCacheWhereInput | Prisma.PrayerCacheWhereInput[]
  id?: Prisma.IntFilter<"PrayerCache"> | number
  date?: Prisma.DateTimeFilter<"PrayerCache"> | Date | string
  fajr?: Prisma.StringFilter<"PrayerCache"> | string
  dhuhr?: Prisma.StringFilter<"PrayerCache"> | string
  asr?: Prisma.StringFilter<"PrayerCache"> | string
  maghrib?: Prisma.StringFilter<"PrayerCache"> | string
  isha?: Prisma.StringFilter<"PrayerCache"> | string
  createdAt?: Prisma.DateTimeFilter<"PrayerCache"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PrayerCache"> | Date | string
}

export type PrayerCacheOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  fajr?: Prisma.SortOrder
  dhuhr?: Prisma.SortOrder
  asr?: Prisma.SortOrder
  maghrib?: Prisma.SortOrder
  isha?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrayerCacheWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  date?: Date | string
  AND?: Prisma.PrayerCacheWhereInput | Prisma.PrayerCacheWhereInput[]
  OR?: Prisma.PrayerCacheWhereInput[]
  NOT?: Prisma.PrayerCacheWhereInput | Prisma.PrayerCacheWhereInput[]
  fajr?: Prisma.StringFilter<"PrayerCache"> | string
  dhuhr?: Prisma.StringFilter<"PrayerCache"> | string
  asr?: Prisma.StringFilter<"PrayerCache"> | string
  maghrib?: Prisma.StringFilter<"PrayerCache"> | string
  isha?: Prisma.StringFilter<"PrayerCache"> | string
  createdAt?: Prisma.DateTimeFilter<"PrayerCache"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PrayerCache"> | Date | string
}, "id" | "date">

export type PrayerCacheOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  fajr?: Prisma.SortOrder
  dhuhr?: Prisma.SortOrder
  asr?: Prisma.SortOrder
  maghrib?: Prisma.SortOrder
  isha?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PrayerCacheCountOrderByAggregateInput
  _avg?: Prisma.PrayerCacheAvgOrderByAggregateInput
  _max?: Prisma.PrayerCacheMaxOrderByAggregateInput
  _min?: Prisma.PrayerCacheMinOrderByAggregateInput
  _sum?: Prisma.PrayerCacheSumOrderByAggregateInput
}

export type PrayerCacheScalarWhereWithAggregatesInput = {
  AND?: Prisma.PrayerCacheScalarWhereWithAggregatesInput | Prisma.PrayerCacheScalarWhereWithAggregatesInput[]
  OR?: Prisma.PrayerCacheScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PrayerCacheScalarWhereWithAggregatesInput | Prisma.PrayerCacheScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PrayerCache"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"PrayerCache"> | Date | string
  fajr?: Prisma.StringWithAggregatesFilter<"PrayerCache"> | string
  dhuhr?: Prisma.StringWithAggregatesFilter<"PrayerCache"> | string
  asr?: Prisma.StringWithAggregatesFilter<"PrayerCache"> | string
  maghrib?: Prisma.StringWithAggregatesFilter<"PrayerCache"> | string
  isha?: Prisma.StringWithAggregatesFilter<"PrayerCache"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PrayerCache"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PrayerCache"> | Date | string
}

export type PrayerCacheCreateInput = {
  date: Date | string
  fajr: string
  dhuhr: string
  asr: string
  maghrib: string
  isha: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrayerCacheUncheckedCreateInput = {
  id?: number
  date: Date | string
  fajr: string
  dhuhr: string
  asr: string
  maghrib: string
  isha: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrayerCacheUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fajr?: Prisma.StringFieldUpdateOperationsInput | string
  dhuhr?: Prisma.StringFieldUpdateOperationsInput | string
  asr?: Prisma.StringFieldUpdateOperationsInput | string
  maghrib?: Prisma.StringFieldUpdateOperationsInput | string
  isha?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrayerCacheUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fajr?: Prisma.StringFieldUpdateOperationsInput | string
  dhuhr?: Prisma.StringFieldUpdateOperationsInput | string
  asr?: Prisma.StringFieldUpdateOperationsInput | string
  maghrib?: Prisma.StringFieldUpdateOperationsInput | string
  isha?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrayerCacheCreateManyInput = {
  id?: number
  date: Date | string
  fajr: string
  dhuhr: string
  asr: string
  maghrib: string
  isha: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrayerCacheUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fajr?: Prisma.StringFieldUpdateOperationsInput | string
  dhuhr?: Prisma.StringFieldUpdateOperationsInput | string
  asr?: Prisma.StringFieldUpdateOperationsInput | string
  maghrib?: Prisma.StringFieldUpdateOperationsInput | string
  isha?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrayerCacheUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fajr?: Prisma.StringFieldUpdateOperationsInput | string
  dhuhr?: Prisma.StringFieldUpdateOperationsInput | string
  asr?: Prisma.StringFieldUpdateOperationsInput | string
  maghrib?: Prisma.StringFieldUpdateOperationsInput | string
  isha?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrayerCacheCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  fajr?: Prisma.SortOrder
  dhuhr?: Prisma.SortOrder
  asr?: Prisma.SortOrder
  maghrib?: Prisma.SortOrder
  isha?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrayerCacheAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PrayerCacheMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  fajr?: Prisma.SortOrder
  dhuhr?: Prisma.SortOrder
  asr?: Prisma.SortOrder
  maghrib?: Prisma.SortOrder
  isha?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrayerCacheMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  fajr?: Prisma.SortOrder
  dhuhr?: Prisma.SortOrder
  asr?: Prisma.SortOrder
  maghrib?: Prisma.SortOrder
  isha?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrayerCacheSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type PrayerCacheSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  fajr?: boolean
  dhuhr?: boolean
  asr?: boolean
  maghrib?: boolean
  isha?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["prayerCache"]>

export type PrayerCacheSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  fajr?: boolean
  dhuhr?: boolean
  asr?: boolean
  maghrib?: boolean
  isha?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["prayerCache"]>

export type PrayerCacheSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  fajr?: boolean
  dhuhr?: boolean
  asr?: boolean
  maghrib?: boolean
  isha?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["prayerCache"]>

export type PrayerCacheSelectScalar = {
  id?: boolean
  date?: boolean
  fajr?: boolean
  dhuhr?: boolean
  asr?: boolean
  maghrib?: boolean
  isha?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PrayerCacheOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "fajr" | "dhuhr" | "asr" | "maghrib" | "isha" | "createdAt" | "updatedAt", ExtArgs["result"]["prayerCache"]>

export type $PrayerCachePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PrayerCache"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    date: Date
    fajr: string
    dhuhr: string
    asr: string
    maghrib: string
    isha: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["prayerCache"]>
  composites: {}
}

export type PrayerCacheGetPayload<S extends boolean | null | undefined | PrayerCacheDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload, S>

export type PrayerCacheCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PrayerCacheFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PrayerCacheCountAggregateInputType | true
  }

export interface PrayerCacheDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PrayerCache'], meta: { name: 'PrayerCache' } }
  /**
   * Find zero or one PrayerCache that matches the filter.
   * @param {PrayerCacheFindUniqueArgs} args - Arguments to find a PrayerCache
   * @example
   * // Get one PrayerCache
   * const prayerCache = await prisma.prayerCache.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PrayerCacheFindUniqueArgs>(args: Prisma.SelectSubset<T, PrayerCacheFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PrayerCacheClient<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PrayerCache that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PrayerCacheFindUniqueOrThrowArgs} args - Arguments to find a PrayerCache
   * @example
   * // Get one PrayerCache
   * const prayerCache = await prisma.prayerCache.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PrayerCacheFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PrayerCacheFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrayerCacheClient<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PrayerCache that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrayerCacheFindFirstArgs} args - Arguments to find a PrayerCache
   * @example
   * // Get one PrayerCache
   * const prayerCache = await prisma.prayerCache.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PrayerCacheFindFirstArgs>(args?: Prisma.SelectSubset<T, PrayerCacheFindFirstArgs<ExtArgs>>): Prisma.Prisma__PrayerCacheClient<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PrayerCache that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrayerCacheFindFirstOrThrowArgs} args - Arguments to find a PrayerCache
   * @example
   * // Get one PrayerCache
   * const prayerCache = await prisma.prayerCache.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PrayerCacheFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PrayerCacheFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrayerCacheClient<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PrayerCaches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrayerCacheFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PrayerCaches
   * const prayerCaches = await prisma.prayerCache.findMany()
   * 
   * // Get first 10 PrayerCaches
   * const prayerCaches = await prisma.prayerCache.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const prayerCacheWithIdOnly = await prisma.prayerCache.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PrayerCacheFindManyArgs>(args?: Prisma.SelectSubset<T, PrayerCacheFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PrayerCache.
   * @param {PrayerCacheCreateArgs} args - Arguments to create a PrayerCache.
   * @example
   * // Create one PrayerCache
   * const PrayerCache = await prisma.prayerCache.create({
   *   data: {
   *     // ... data to create a PrayerCache
   *   }
   * })
   * 
   */
  create<T extends PrayerCacheCreateArgs>(args: Prisma.SelectSubset<T, PrayerCacheCreateArgs<ExtArgs>>): Prisma.Prisma__PrayerCacheClient<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PrayerCaches.
   * @param {PrayerCacheCreateManyArgs} args - Arguments to create many PrayerCaches.
   * @example
   * // Create many PrayerCaches
   * const prayerCache = await prisma.prayerCache.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PrayerCacheCreateManyArgs>(args?: Prisma.SelectSubset<T, PrayerCacheCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PrayerCaches and returns the data saved in the database.
   * @param {PrayerCacheCreateManyAndReturnArgs} args - Arguments to create many PrayerCaches.
   * @example
   * // Create many PrayerCaches
   * const prayerCache = await prisma.prayerCache.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PrayerCaches and only return the `id`
   * const prayerCacheWithIdOnly = await prisma.prayerCache.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PrayerCacheCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PrayerCacheCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PrayerCache.
   * @param {PrayerCacheDeleteArgs} args - Arguments to delete one PrayerCache.
   * @example
   * // Delete one PrayerCache
   * const PrayerCache = await prisma.prayerCache.delete({
   *   where: {
   *     // ... filter to delete one PrayerCache
   *   }
   * })
   * 
   */
  delete<T extends PrayerCacheDeleteArgs>(args: Prisma.SelectSubset<T, PrayerCacheDeleteArgs<ExtArgs>>): Prisma.Prisma__PrayerCacheClient<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PrayerCache.
   * @param {PrayerCacheUpdateArgs} args - Arguments to update one PrayerCache.
   * @example
   * // Update one PrayerCache
   * const prayerCache = await prisma.prayerCache.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PrayerCacheUpdateArgs>(args: Prisma.SelectSubset<T, PrayerCacheUpdateArgs<ExtArgs>>): Prisma.Prisma__PrayerCacheClient<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PrayerCaches.
   * @param {PrayerCacheDeleteManyArgs} args - Arguments to filter PrayerCaches to delete.
   * @example
   * // Delete a few PrayerCaches
   * const { count } = await prisma.prayerCache.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PrayerCacheDeleteManyArgs>(args?: Prisma.SelectSubset<T, PrayerCacheDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PrayerCaches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrayerCacheUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PrayerCaches
   * const prayerCache = await prisma.prayerCache.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PrayerCacheUpdateManyArgs>(args: Prisma.SelectSubset<T, PrayerCacheUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PrayerCaches and returns the data updated in the database.
   * @param {PrayerCacheUpdateManyAndReturnArgs} args - Arguments to update many PrayerCaches.
   * @example
   * // Update many PrayerCaches
   * const prayerCache = await prisma.prayerCache.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PrayerCaches and only return the `id`
   * const prayerCacheWithIdOnly = await prisma.prayerCache.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PrayerCacheUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PrayerCacheUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PrayerCache.
   * @param {PrayerCacheUpsertArgs} args - Arguments to update or create a PrayerCache.
   * @example
   * // Update or create a PrayerCache
   * const prayerCache = await prisma.prayerCache.upsert({
   *   create: {
   *     // ... data to create a PrayerCache
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PrayerCache we want to update
   *   }
   * })
   */
  upsert<T extends PrayerCacheUpsertArgs>(args: Prisma.SelectSubset<T, PrayerCacheUpsertArgs<ExtArgs>>): Prisma.Prisma__PrayerCacheClient<runtime.Types.Result.GetResult<Prisma.$PrayerCachePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PrayerCaches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrayerCacheCountArgs} args - Arguments to filter PrayerCaches to count.
   * @example
   * // Count the number of PrayerCaches
   * const count = await prisma.prayerCache.count({
   *   where: {
   *     // ... the filter for the PrayerCaches we want to count
   *   }
   * })
  **/
  count<T extends PrayerCacheCountArgs>(
    args?: Prisma.Subset<T, PrayerCacheCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PrayerCacheCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PrayerCache.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrayerCacheAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PrayerCacheAggregateArgs>(args: Prisma.Subset<T, PrayerCacheAggregateArgs>): Prisma.PrismaPromise<GetPrayerCacheAggregateType<T>>

  /**
   * Group by PrayerCache.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrayerCacheGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PrayerCacheGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PrayerCacheGroupByArgs['orderBy'] }
      : { orderBy?: PrayerCacheGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PrayerCacheGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPrayerCacheGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PrayerCache model
 */
readonly fields: PrayerCacheFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PrayerCache.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PrayerCacheClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PrayerCache model
 */
export interface PrayerCacheFieldRefs {
  readonly id: Prisma.FieldRef<"PrayerCache", 'Int'>
  readonly date: Prisma.FieldRef<"PrayerCache", 'DateTime'>
  readonly fajr: Prisma.FieldRef<"PrayerCache", 'String'>
  readonly dhuhr: Prisma.FieldRef<"PrayerCache", 'String'>
  readonly asr: Prisma.FieldRef<"PrayerCache", 'String'>
  readonly maghrib: Prisma.FieldRef<"PrayerCache", 'String'>
  readonly isha: Prisma.FieldRef<"PrayerCache", 'String'>
  readonly createdAt: Prisma.FieldRef<"PrayerCache", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PrayerCache", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PrayerCache findUnique
 */
export type PrayerCacheFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * Filter, which PrayerCache to fetch.
   */
  where: Prisma.PrayerCacheWhereUniqueInput
}

/**
 * PrayerCache findUniqueOrThrow
 */
export type PrayerCacheFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * Filter, which PrayerCache to fetch.
   */
  where: Prisma.PrayerCacheWhereUniqueInput
}

/**
 * PrayerCache findFirst
 */
export type PrayerCacheFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * Filter, which PrayerCache to fetch.
   */
  where?: Prisma.PrayerCacheWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrayerCaches to fetch.
   */
  orderBy?: Prisma.PrayerCacheOrderByWithRelationInput | Prisma.PrayerCacheOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PrayerCaches.
   */
  cursor?: Prisma.PrayerCacheWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrayerCaches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrayerCaches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrayerCaches.
   */
  distinct?: Prisma.PrayerCacheScalarFieldEnum | Prisma.PrayerCacheScalarFieldEnum[]
}

/**
 * PrayerCache findFirstOrThrow
 */
export type PrayerCacheFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * Filter, which PrayerCache to fetch.
   */
  where?: Prisma.PrayerCacheWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrayerCaches to fetch.
   */
  orderBy?: Prisma.PrayerCacheOrderByWithRelationInput | Prisma.PrayerCacheOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PrayerCaches.
   */
  cursor?: Prisma.PrayerCacheWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrayerCaches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrayerCaches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrayerCaches.
   */
  distinct?: Prisma.PrayerCacheScalarFieldEnum | Prisma.PrayerCacheScalarFieldEnum[]
}

/**
 * PrayerCache findMany
 */
export type PrayerCacheFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * Filter, which PrayerCaches to fetch.
   */
  where?: Prisma.PrayerCacheWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrayerCaches to fetch.
   */
  orderBy?: Prisma.PrayerCacheOrderByWithRelationInput | Prisma.PrayerCacheOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PrayerCaches.
   */
  cursor?: Prisma.PrayerCacheWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrayerCaches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrayerCaches.
   */
  skip?: number
  distinct?: Prisma.PrayerCacheScalarFieldEnum | Prisma.PrayerCacheScalarFieldEnum[]
}

/**
 * PrayerCache create
 */
export type PrayerCacheCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * The data needed to create a PrayerCache.
   */
  data: Prisma.XOR<Prisma.PrayerCacheCreateInput, Prisma.PrayerCacheUncheckedCreateInput>
}

/**
 * PrayerCache createMany
 */
export type PrayerCacheCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PrayerCaches.
   */
  data: Prisma.PrayerCacheCreateManyInput | Prisma.PrayerCacheCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PrayerCache createManyAndReturn
 */
export type PrayerCacheCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * The data used to create many PrayerCaches.
   */
  data: Prisma.PrayerCacheCreateManyInput | Prisma.PrayerCacheCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PrayerCache update
 */
export type PrayerCacheUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * The data needed to update a PrayerCache.
   */
  data: Prisma.XOR<Prisma.PrayerCacheUpdateInput, Prisma.PrayerCacheUncheckedUpdateInput>
  /**
   * Choose, which PrayerCache to update.
   */
  where: Prisma.PrayerCacheWhereUniqueInput
}

/**
 * PrayerCache updateMany
 */
export type PrayerCacheUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PrayerCaches.
   */
  data: Prisma.XOR<Prisma.PrayerCacheUpdateManyMutationInput, Prisma.PrayerCacheUncheckedUpdateManyInput>
  /**
   * Filter which PrayerCaches to update
   */
  where?: Prisma.PrayerCacheWhereInput
  /**
   * Limit how many PrayerCaches to update.
   */
  limit?: number
}

/**
 * PrayerCache updateManyAndReturn
 */
export type PrayerCacheUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * The data used to update PrayerCaches.
   */
  data: Prisma.XOR<Prisma.PrayerCacheUpdateManyMutationInput, Prisma.PrayerCacheUncheckedUpdateManyInput>
  /**
   * Filter which PrayerCaches to update
   */
  where?: Prisma.PrayerCacheWhereInput
  /**
   * Limit how many PrayerCaches to update.
   */
  limit?: number
}

/**
 * PrayerCache upsert
 */
export type PrayerCacheUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * The filter to search for the PrayerCache to update in case it exists.
   */
  where: Prisma.PrayerCacheWhereUniqueInput
  /**
   * In case the PrayerCache found by the `where` argument doesn't exist, create a new PrayerCache with this data.
   */
  create: Prisma.XOR<Prisma.PrayerCacheCreateInput, Prisma.PrayerCacheUncheckedCreateInput>
  /**
   * In case the PrayerCache was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PrayerCacheUpdateInput, Prisma.PrayerCacheUncheckedUpdateInput>
}

/**
 * PrayerCache delete
 */
export type PrayerCacheDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
  /**
   * Filter which PrayerCache to delete.
   */
  where: Prisma.PrayerCacheWhereUniqueInput
}

/**
 * PrayerCache deleteMany
 */
export type PrayerCacheDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PrayerCaches to delete
   */
  where?: Prisma.PrayerCacheWhereInput
  /**
   * Limit how many PrayerCaches to delete.
   */
  limit?: number
}

/**
 * PrayerCache without action
 */
export type PrayerCacheDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrayerCache
   */
  select?: Prisma.PrayerCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrayerCache
   */
  omit?: Prisma.PrayerCacheOmit<ExtArgs> | null
}
