
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const NotificationType = {
  AZAN: 'AZAN',
  EVENT_ISLAMIC: 'EVENT_ISLAMIC',
  CUSTOM: 'CUSTOM'
} as const

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]
